version: '3'

networks:
  backend-db-test:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: /var/lib/postgresql/data/unittest/
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend-db-test
  backend:
    container_name: dbcontext_test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend-db-test
    depends_on:
      - postgres